language: ruby
sudo: false
cache: bundler
before_script:
  - bundle update

rvm:
  - ruby-head
  - 2.5.1
  - 2.4.4
  - 2.3.7

os:
  - linux
  # - osx

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head

env:
  global:
    - TEST=true

script: bundle exec rake test
