language: ruby

rvm:
  - ruby-head
  - 2.2.3
  - 2.1.7
  - 2.0.0
  - 1.9.3
  - jruby-19mode

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-19mode

script: bundle exec rake test

env: TEST=true
