language: ruby

rvm:
  - ruby-head
  - 2.1.2
  - 2.0.0
  - 1.9.3
  - jruby-19mode

# Bug in jRuby w/ Rouge: https://github.com/jruby/jruby/issues/1392
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-19mode

script: "bundle exec rake test"

env: TEST=true
